framework:
    messenger:
        default_bus: command.sync.bus
        buses:
            command.sync.bus:
                middleware:
                    - doctrine_close_connection
                    - doctrine_transaction
            command.async.bus:
                middleware:
                    - doctrine_close_connection
                    - doctrine_transaction
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        transports:
            sync:
                dsn: 'sync://'
            async:
                dsn: '%env(MESSENGER_RABBITMQ_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                        default_publish_routing_key: commands
                    queues:
                        commands:
                            binding_keys:
                                - commands
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
            failed:
                dsn: '%env(MESSENGER_DOCTRINE_TRANSPORT_DSN)%'
                options:
                    queue_name: failed
                    auto_setup: false
        failure_transport: failed
        routing:
            Bingely\Shared\Application\Command\Sync\Command: sync
            Bingely\Shared\Application\Command\Async\Command: async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
