# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    tmdb.api.key: '%env(TMDB_API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Bingely\:
        resource: '../src/'
        exclude:
            - '../src/*/Domain/Entity/'
            - '../src/Shared/Infrastructure/Symfony/Kernel.php'

    _instanceof:
        Bingely\Shared\Application\Command\Sync\CommandHandler:
            tags:
                - { name: 'messenger.message_handler', bus: 'command.sync.bus' }
        Bingely\Shared\Application\Command\Async\CommandHandler:
            tags:
                - { name: 'messenger.message_handler', bus: 'command.async.bus' }

    # API Exception Listener
    Bingely\Shared\Infrastructure\Symfony\EventListener\ApiExceptionListener:
        arguments:
            $environment: '%kernel.environment%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
